excel_df_columns = {
    "h1": [
        "ppm",
        "integral",
        "jCouplingClass",
        "jCouplingVals",
        "range",
        "label",
        "f1H_i",
        "f2H_i",
        "f1_i",
        "f2_i",
    ],
    "c13": [
        "ppm",
        "attached_protons",
        "ppmH1s",
        "max_bonds",
        "label",
        "f2C_i",
        "f1C_i",
        "f1_i",
        "f2_i",
    ],
    "pureshift": [
        "ppm",
        "intensity",
        "Width",
        "Area",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "cosy": [
        "f1_ppm",
        "f2_ppm",
        "intensity",
        "f1_i",
        "f1p_i",
        "f2_i",
        "f2p_i",
        "f1p_ppm",
        "f2p_ppm",
        "f1H_i",
        "f2H_i",
        "f1Cp_i",
        "f2Cp_i",
    ],
    "noesy": [
        "f1_ppm",
        "f2_ppm",
        "intensity",
        "f1_i",
        "f1p_i",
        "f2_i",
        "f2p_i",
        "f1p_ppm",
        "f2p_ppm",
        "f1H_i",
        "f2H_i",
        "f1Cp_i",
        "f2Cp_i",
    ],
    "hsqc": [
        "f1_ppm",
        "f2_ppm",
        "intensity",
        "f1_i",
        "f2_i",
        "f2p_i",
        "f1C_i",
        "f2H_i",
        "f2Cp_i",
        "f2p_ppm",
    ],
    "hsqc_CH_only": [
        "f1_ppm",
        "f2_ppm",
        "intensity",
        "f1_i",
        "f2_i",
        "f2p_i",
        "f1C_i",
        "f2H_i",
        "f2Cp_i",
        "f2p_ppm",
    ],
    "hmbc": [
        "f1_ppm",
        "f2_ppm",
        "intensity",
        "f2p_ppm",
        "f1_i",
        "f2_i",
        "f2p_i",
        "f1C_i",
        "f2H_i",
        "f2Cp_i",
    ],
}

excel_orig_df_columns = {
    "molecule": ["molecule", "smiles"],
    "H1_1D": ["Name", "Shift", "Range", "H's", "Integral", "Class", "J's", "Method"],
    "C13_1D": [
        "ppm",
        "Intensity",
        "Width",
        "Area",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "H1_pureshift": [
        "ppm",
        "Intensity",
        "Width",
        "Area",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "COSY": [
        "f2 (ppm)",
        "f1 (ppm)",
        "Intensity",
        "Width f2",
        "Width f1",
        "Volume",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "HSQC": [
        "f2 (ppm)",
        "f1 (ppm)",
        "Intensity",
        "Width f2",
        "Width f1",
        "Volume",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "HSQC_CH": [
        "f2 (ppm)",
        "f1 (ppm)",
        "Intensity",
        "Width f2",
        "Width f1",
        "Volume",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "HMBC": [
        "f2 (ppm)",
        "f1 (ppm)",
        "Intensity",
        "Width f2",
        "Width f1",
        "Volume",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
    "NOESY": [
        "f2 (ppm)",
        "f1 (ppm)",
        "Intensity",
        "Width f2",
        "Width f1",
        "Volume",
        "Type",
        "Flags",
        "Impurity/Compound",
        "Annotation",
    ],
}
